version: '3.6'

services:

    scheduler:
        image: sip_dask_workflow_example
        hostname: dask-scheduler
        ports:
            - 8787:8787  # Bokeh Dask UI?
            - 8786:8786  # Dask scheduler port
        command: ["dask-scheduler"]
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M

    worker:
        image: sip_dask_workflow_example
        hostname: dask-worker
        command: ["dask-worker", "scheduler:8786"]
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
