version: '3.6'

services:

  config_db:
    image: redis:5.0.1-alpine
    ports:
      - 6379:6379

  redis-commander-db0:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=config_db:config_db:6379:0
    ports:
    - 8081:8081

#  redis-commander-db0:
#    image: tenstartups/redis-commander:latest
#    command: ["--redis-host", "config_db"]
#    ports:
#    - 8081:8081

  portainer:
    image: portainer/portainer:1.19.2
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
