sudo: required

dist: xenial

notifications:
  slack: ska-sip:zgaO4jJWwB4UjFRulowC5g56

services:
- docker

language: python

python:
- 3.6

cache: pip

stages:
  - tests

jobs:
  include:

  # Run linters and unit tests
  # -------------------------------------------------------------------------
  - stage: tests
  # Execution Control: Configuration database
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/configuration_db/requirements.txt
    before_script:
    - docker swarm init
    - docker service create -p 6379:6379 --name=config_db redis:5.0.1-alpine
    script: ./tools/run_tests.sh sip/execution_control/configuration_db
  -
  # Execution Control: Processing Block Controller
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/processing_block_controller/requirements.txt
    before_script:
    - docker swarm init
    - docker service create -p 6379:6379 --name=config_db redis:5.0.1-alpine
    script:
    - ./tools/run_tests.sh sip/execution_control/processing_block_controller
  -
  # Execution Control: Master Controller
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/master_controller/requirements.txt
    script: ./tools/run_tests.sh sip/execution_control/master_controller
  -
  # Tango Control: Flask Master
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/tango_control/flask_master/requirements.txt
    script: ./tools/run_tests.sh sip/tango_control/flask_master
  -
  # Platform: logging
    install:
    - pip install -r testing_requirements.txt
    script: ./tools/run_tests.sh sip/platform/logging

  # Run test coverage analysis
  - stage: test_coverage
    script: true
    after_success: codecov
