sudo: required

dist: xenial

notifications:
  slack: ska-sip:zgaO4jJWwB4UjFRulowC5g56

services:
- docker

language: python

python:
- 3.6

cache: pip

stages:
  - tests

jobs:
  include:

  # [Execution Control] Configuration database
  - stage: test
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/configuration_db/requirements.txt
    before_script:
    - docker swarm init
    - docker service create -p 6379:6379 --name=config_db redis:5.0.1-alpine
    script: ./tools/run_tests.sh sip/execution_control/configuration_db
    after_success: codecov
  # [Execution Control] Processing Block Controller
  - stage: test
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/processing_block_controller/requirements.txt
    before_script:
    - docker swarm init
    - docker service create -p 6379:6379 --name=config_db redis:5.0.1-alpine
    script:
    - ./tools/run_tests.sh sip/execution_control/processing_block_controller
    after_success: codecov
  # [Execution Control] Master Controller
  - stage: test
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/execution_control/master_controller/requirements.txt
    script: ./tools/run_tests.sh sip/execution_control/master_controller
    after_success: codecov
  # [Tango Control] Flask Master
  - stage: test
    install:
    - pip install -r testing_requirements.txt
    - pip install -r sip/tango_control/flask_master/requirements.txt
    script: ./tools/run_tests.sh sip/tango_control/flask_master
    after_success: codecov
  # [Platform] logging
  - stage: test
    install:
    - pip install -r testing_requirements.txt
    script: ./tools/run_tests.sh sip/platform/logging
    after_success: codecov
