language: python
python:
  - "3.6"
cache: pip
install:
  - pip install pylint>=1.9.0
  - pip install pycodestyle>=2.4.0
script:
  - pycodestyle --exclude=receive_visibilities sip
  - find . -iname "*.py" | xargs pylint
