version: '3.4'

services:

  # Mysql database set up for use with Tango
  tango-db:
    image: tangocs/mysql:9.2.2
    ports:
      - 9999:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
       - tango-db:/var/lib/mysql
    networks:
      - tango

  # Tango DataBaseds ++
  tango-cs:
    image: tangocs/tango-cs:9
    ports:
      - 10000:10000
    environment:
      - TANGO_HOST=localhost:10000
      - MYSQL_HOST=tango-db:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango
    networks:
      - tango
    depends_on:
      - tango-db

  # Test container with Tango, PyTango, and ipython3
  pytango-example:
    image: skasip/pytango-example
    command: sleep 3600
    environment:
      - TANGO_HOST=tango-cs:10000
      - MYSQL_HOST=tango-db:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TANGO_HOST: tango-db:3306
    networks:
      - tango
    depends_on:
      - tango-db

networks:
  tango:

volumes:
  tango-db:
