version: '3.6'

services:

  tango_mysql:
    image: skasip/tango_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sip1
    volumes:
      - tangodb:/var/lib/mysql
    build:
      context: tango_mysql

  tango_db:
    image: skasip/tango_db
    ports:
      - 10000:10000
    environment:
      - TANGO_HOST=localhost:10000
      - MYSQL_HOST=tango_mysql:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango
    depends_on:
      - tango_mysql
    build:
      context: tango_db

volumes:
  tangodb:
