#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" ; pwd -P)"/incl.sh

if [[ "$#" -ne 1 ]]; then
    echo "usage: $0 service_name"
    exit "0"
fi

NAME="sip_$1"
echo -e "$(docker ps -f name='sip*')"
echo -e "---------------------------------------"
echo -e "NAME = ${NAME}"
echo -e "---------------------------------------"
CONTAINERS="$(docker ps -f name=${NAME}*)"
echo -e "${CONTAINERS}"
echo -e "---------------------------------------"
CONTAINER_IDS="$(docker ps -q -f name=${NAME}*)"

echo_blue "Killing container:"
for CONTAINER_ID in ${CONTAINER_IDS[@]}; do
    echo_red "- ${CONTAINER_ID}"
    docker kill "${CONTAINER_ID}"
    echo_blue " Waiting for service ${NAME} to restart"
    docker service ls -f name=${NAME}
    while true; do
        SERVICE_ID="$(docker service ps -q -f desired-state=running "${NAME}")"
        if [[ ! -z "${SERVICE_ID}" ]]; then
            echo -e "-- ${BLUE} Service started!! ID = ${SERVICE_ID}${NC}"
            sleep "1"
            docker service ls -f name=${NAME}
            break
        fi
    done


done


