version: "3.6"

services:

    fluentd:
        image: fluent/fluentd:v1.3
        volumes:
            - ./output:/fluentd/log
        deploy:
            replicas: 1
        configs:
            - source: fluentd
              target: "/fluentd/etc/fluent.conf"
              mode: 0644
        networks:
            - host

    log_spammer:
        image: skasip/log_spammer:1.0.4
        command: ["0.1", "--timestamp-us", "--show-thread"]
        deploy:
            replicas: 1
        logging:
            driver: fluentd
            options:
                tag: "{{.ImageName}}~{{.Name}}~{{.ID}}"
        networks:
            - host

configs:
    fluentd:
        file: ./fluentd/fluent.conf

networks:
    host:
        external: true
        name: host
