version: "3.6"

services:

    log_spammer:
        image: skasip/log_spammer:1.0.2
        command: ["0.1"]
        deploy:
            replicas: 1
        logging:
            driver: fluentd
            options:
                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        networks:
            - host


networks:
    host:
        external: true
        name: host
