version: '3.6'

services:

  tango_master:
    # This version should be frozen for the demos (updates can overwrite this version)
    image: skasip/tango_master:1.0.8
    environment:
      - TANGO_HOST=tango_database:10000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_master/scripts:/home/sip/scripts
      - ./tango_master/app:/home/sip/app

  tango_database:
    # This version should now be frozen for the demos
    image: skasip/tango_database:1.0.4
    ports:
    - 10000:10000
    environment:
    - MYSQL_HOST=tango_mysql:3306
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - MYSQL_DATABASE=tango_db
    deploy:
      placement:
        constraints:
        - node.role == manager

  tango_mysql:
    # This version should now be frozen for the demos
    image: skasip/tango_mysql:1.0.3
    environment:
    - MYSQL_ROOT_PASSWORD=sip1
    volumes:
    - tangodb:/var/lib/mysql:consistent

  config_database:
    image: redis:4.0.6-alpine
    ports:
    - 6379:6379
    volumes:
    - config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    ports:
    - 8081:8081

volumes:
  config_database:
  tangodb:
