# Docker compose script for starting a set of mock services used to develop
# the Processing Controller Scheduler.
version: '3.6'

services:

  config_db:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1

  pbc:
    image: skasip/mock_pbc
    environment:
      - CELERY_BROKER=redis://config_db/1
      - CELERY_BACKEND=redis://config_db/2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - conf_db

  redis_ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=config_db:config_db:6379:0
    ports:
      - 8081:8081
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - conf_db

