version: '3.6'

services:
    recv:
        image: skasip/vis_recv_c:1.1.9
        # command args (all optional):
        # num_streams, num_threads, num_times_in_buffer, num_buffers, port_start
        command: ["60", "4", "4"]
        #volumes:
        #    - type: bind
        #      source: /mnt/ceph
        #      target: /app/output
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.recv == 01
        networks:
            - hostnet
        stop_signal: INT
    send:
        image: skasip/csp_vis_sender
        command:
            ['{
                "destination_host": "127.0.0.1",
                "destination_port_start": 41000,
                "heap":
                {
                    "num_stations": 512,
                    "num_pols": 4
                },
                "max_duration_sec": -1,
                "num_streams": 60,
                "num_workers": 4,
                "reporting_interval_sec": 1,
                "start_channel": 0,
                "stream_config":
                {
                    "max_packet_size": 8972,
                    "rate": 7.1e6,
                    "burst_size": 1472,
                    "max_heaps": 2
                }
            }']
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.send == 01
        networks:
            - hostnet
        stop_signal: INT

networks:
    hostnet:
        external: true
        name: host
