version: '3.6'

services:
    recv:
        image: skasip/vis_recv_c:1.3.2
        # command args (all optional):
        #     1. num_streams
        #     2. num_threads_recv
        #     3. num_threads_write
        #     4. num_times_in_buffer
        #     5. max_num_buffers
        #     6. port_start
        #     7. num_channels_per_file
        #     8. output_dir
        command: ["60", "2", "2", "4", "3", "41000", "4", "."]
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.recv == 01
        networks:
            - hostnet
        stop_signal: INT
    send:
        image: skasip/csp_vis_sender:1.1.0
        command:
            ['{
                "destination_host": "127.0.0.1",
                "destination_port_start": 41000,
                "heap":
                {
                    "num_stations": 512,
                    "num_pols": 4
                },
                "max_duration_sec": -1,
                "num_streams": 60,
                "num_workers": 4,
                "reporting_interval_sec": 1,
                "start_channel": 0,
                "stream_config":
                {
                    "max_packet_size": 8972,
                    "rate": 7.1e6,
                    "burst_size": 1472,
                    "max_heaps": 2
                }
            }']
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.send == 01
        networks:
            - hostnet
        stop_signal: INT

networks:
    hostnet:
        external: true
        name: host
