version: '3.7'

services:
    recv:
        image: skasip/ingest_visibilities
        command: >
            '{
                "port_start": 41000,
                "memory_pool":
                {
                    "lower": 1048576,
                    "upper": 4718592,
                    "max_free": 16,
                    "initial": 16
                },
                "num_buffers": 2,
                "num_buffer_times": 4,
                "num_streams": 10,
                "process_data": true,
                "write_data": false,
                "filename": "test_receive.dat"
            }'
        #volumes:
        #    - type: bind
        #      source: /mnt/ceph
        #      target: /app/output
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.recv == 01
        networks:
            - hostnet
        stop_signal: INT
    send:
        image: skasip/csp_vis_sender
        command: >
            '{
                "destination_host": "127.0.0.1",
                "destination_port_start": 41000,
                "heap":
                {
                    "num_stations": 512,
                    "num_pols": 4
                },
                "max_duration_sec": -1,
                "num_streams": 10,
                "num_workers": 4,
                "reporting_interval_sec": 1,
                "start_channel": 0,
                "stream_config":
                {
                    "max_packet_size": 9172,
                    "rate": 7.1e6,
                    "burst_size": 1472,
                    "max_heaps": 2
                }
            }'
        deploy:
            restart_policy:
                condition: none
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.send == 01
        networks:
            - hostnet
        stop_signal: INT

networks:
    hostnet:
        external: true
        name: host
