version: '3.6'

services:

    scheduler:
        image: skasip/dask_scheduler_base
        ports:
            - 8787:8787  # Bokeh Dask UI?
            - 8786:8786  # Dask scheduler port
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        # networks:
        #     - host
        #     - workflow_02

    worker:
        image: skasip/dask_workflow_test_02
        command: --nprocs 1 --nthreads 2 --memory-limit 2GB scheduler:8786
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        # networks:
        #     - host
        #     - workflow_02


    # run_workflow:
    #     image: skasip/dask_workflow_test_02
    #     entrypoint: python3
    #     command: -m workflow
    #     environment:
    #         - DASK_SCHEDULER_HOST=scheduler
    #         - DASK_SCHEDULER_PORT=8786
    #     deploy:
    #         mode: replicated
    #         replicas: 1
    #         resources:
    #             limits:
    #                 cpus: '1.0'
    #                 memory: 1024M
#         networks:
#             - workflow_02
#             - host

# networks:
#     host:
#         name: host
#     workflow_02:
#         driver: overlay