version: '3.6'

services:

    scheduler:
        image: skasip/dask_scheduler_base
        ports:
            - 8787:8787  # Bokeh Dask UI?
            - 8786:8786  # Dask scheduler port
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M

    worker:
        image: skasip/dask_workflow_test_02
        command: ["scheduler:8786"]
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
