version: '3.6'

services:

    run_workflow:
        image: skasip/dask_workflow_test_02
        entrypoint: python3
        command: -m workflow
        environment:
            - DASK_SCHEDULER_HOST=scheduler
            - DASK_SCHEDULER_PORT=8786
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        networks:
            - workflow_02
            - host


networks:
    host:
        name: host
    workflow_02:
        driver: overlay