#!/bin/bash
# Command line utility to create a new SDP State.
# Uses jq.
myname=${0##*/}
while getopts cds10?h name
do
   case $name in
   c)    jqOpt="-cM" ;;
   d)    state=disable ;;
   s)	 state=standby ;;
   0)    state=off ;;
   1)    state=on ;;
   \?|h)   printf "Usage: %s: -0 | -1 | -s | -d \n" $myname
        printf "   for off, on, standby and disable respectively\n"
        printf "   (default on)\n"
        printf "   Use -c to compact output.\n"
        exit 2;;
   esac
done

jq ${jqOpt} -n --arg state ${state:-on} '{"state":$state}'
