version: '3'

services:

  processing_controller_interface:
    image: skasip/processing_controller_interface_rest
    environment:
      REDIS_HOST: "redis://config_db"
      REDIS_DB_ID: 0
    ports:
      - 5000:5000
    build: .

