version: '3.6'

services:

  pci_flask:
    image: skasip/pci_flask
    environment:
      REDIS_HOST: "redis://config_db"
      REDIS_DB_ID: 0
      SIP_PCI_LOG_LEVEL: 'DEBUG'
    ports:
      - 5000
    build: .

