# Docker compose script for starting a set of mock services used to develop
# the Processing Controller Scheduler.
version: '3.7'

services:

  config_db:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1

  pbc:
    image: skasip/pbc
    environment:
      - CELERY_BROKER=redis://config_db/1
      - CELERY_BACKEND=redis://config_db/2
      - REDIS_HOST=config_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - conf_db

  redis_ui_config_db:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=config_db:config_db:6379:0
    ports:
      - 8081:8081
    depends_on:
      - conf_db

  redis_ui_celery_broker:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=config_db:config_db:6379:1
    ports:
      - 8082:8081
    depends_on:
      - conf_db

  redis_ui_celery_backend:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=config_db:config_db:6379:2
    ports:
      - 8083:8081
    depends_on:
      - conf_db

  redis_ui_celery_pb_queue:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=config_db:config_db:6379:10
      ports:
        - 8084:8081
      depends_on:
        - conf_db
