# Docker compose script for starting a set of mock services used to develop
# the Processing Controller Scheduler.
version: '3.6'

services:

  processing_controller:
    image: skasip/processing_controller:1.2.1
    environment:
    - CELERY_BROKER_URL=redis://config_database/1
    - CELERY_RESULT_BACKEND=redis://config_database/2
    - REDIS_HOST=config_database
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./scheduler:/home/sip/scheduler
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
    - config_database

  pbc:
    image: skasip/processing_block_controller:1.2.2
    environment:
    - CELERY_BROKER_URL=redis://config_database/1
    - CELERY_RESULT_BACKEND=redis://config_database/2
    - REDIS_HOST=config_database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1

  config_database:
    image: redis:5.0.1-alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1

  config_db_ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=config_db:config_database:6379:0
    ports:
      - 8081:8081
