version: '3.6'

services:

  scheduler:
    image: vlad7235/ical_dask_scheduler:latest
    ports:
      - 8786:8786
      - 8787:8787
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - ical_sip

  worker:
    image: vlad7235/ical_dask_worker:latest
    # Memory limit applies to each worker process
    command: scheduler:8786 --nprocs 8 --nthreads 1 --memory-limit 8GB
    depends_on:
      - scheduler
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /var/mnt/ceph/vlad/sdp_arl:/worker/sdp_arl
    environment:
      - ARL_DASK_SCHEDULER=scheduler:8786
      - PYTHONPATH=/worker/sdp_arl
    networks:
      - ical_sip

networks:
  ical_sip:
    external: true
