version: '3.6'

services:

  scheduler:
    image: ical_dask_scheduler
    ports:
      - 8786:8786
      - 8787:8787
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - ical_sip

  worker:
    image: ical_dask_worker
    # Memory limit applies to each worker process
    command: scheduler:8786 --nprocs 2 --nthreads 1 --memory-limit 2GB
    depends_on:
      - scheduler
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ../pipelines/sdp_arl:/worker/sdp_arl
    environment:
      - ARL_DASK_SCHEDULER=scheduler:8786
      - PYTHONPATH=/worker/sdp_arl
    networks:
      - ical_sip

networks:
  ical_sip:
    external: true
