version: '3.6'

services:

    scheduler:
        image: ical_dask_schduler
        ports:
            - 8787:8787
            - 8786:8787
        deploy:
            mode: replicated
            replicas: 1
        networks:
            - ical_sip

    worker:
        image: ical_dask_worker
        depends_on: scheduler
        deploy:
            mode: replicated
            replicas: 1
        volumes:
            - ./algorithm-reference-library:/home/sdp/algorithm-reference-library
        environment:
            - ARL_DASK_SCHEDULER=scheduler:8786
        networks:
            - ical_sip

networks:
    ical_sip:
        external: true
