version: '3.4'

services:

  master:
    image: skasip/master_controller_rest
    environment:
      REDIS_HOST: "master_db"
    ports:
      - 5000
    build: .

  master_db:
    image: redis:4.0.6-alpine
    volumes:
      - master_db:/data/db

  services_watchdog:
    image: skasip/mock_services_watchdog
    environment:
      REDIS_HOST: "master_db"
    build: mock_watchdog

volumes:
  master_db:
