version: '3.6'

services:

  interactive_client:
    image: skasip/tango_interactive_client
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:10000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_interactive_client:/home/sip/tango_interactive_client

  master_client:
    image: skasip/tango_master_client
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:10000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_master_client:/home/sip/tango_master_client

  master:
    image: skasip/tango_master
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:10000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_master:/home/sip/tango_master

  processing_block:
    image: skasip/tango_processing_block
    command: sleep 36000
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    volumes:
    - ./tango_processing_block:/home/sip/tango_processing_block

  subarray:
    image: skasip/tango_subarray
    command: sleep 36000
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    volumes:
    - ./tango_subarray:/home/sip/tango_subarray

  tango_database:
    image: skasip/tango_database:1.0.4
    ports:
      - 20000:10000
    environment:
      - MYSQL_HOST=tango_mysql:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango_db

  tango_mysql:
    image: skasip/tango_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sip1
    volumes:
      - tangodb:/var/lib/mysql

  config_database:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379
    volumes:
      - config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    ports:
    - 8081:8081

volumes:
  config_database:
  tangodb:
