version: '3.6'

services:

  interactive_client:
    image: skasip/tango_interactive_client:latest
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:20000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_interactive_client:/home/sip

  master:
    image: skasip/tango_master:latest
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:20000
      - REDIS_HOST=config_database
    volumes:
      - ./tango_master:/home/sip

  processing_controller:
    image: skasip/tango_processing_controller:latest
    command: sleep 36000
    environment:
    - TANGO_HOST=tango_database:20000
    - REDIS_HOST=config_database
    volumes:
    - ./tango_processing_controller:/home/sip

  subarray:
    image: skasip/tango_subarray:latest
    command: sleep 36000
    environment:
    - TANGO_HOST=tango_database:20000
    - REDIS_HOST=config_database
    volumes:
    - ./tango_subarray:/home/sip

  tango_database:
    image: skasip/tango_database:latest
    ports:
      - 20000:10000
    environment:
      - TANGO_HOST=localhost:20000
      - MYSQL_HOST=tango_mysql:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango_db
    depends_on:
      - tango_mysql

  tango_mysql:
    image: skasip/tango_mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=sip1
    volumes:
      - tangodb:/var/lib/mysql

  config_database:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379
    volumes:
      - config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    ports:
    - 8081:8081

volumes:
  config_database:
  tangodb:
