version: '3.6'

services:

  interactive_client:
    image: skasip/tango_interactive_client:1.0.4
    command: sleep 36000
    environment:
      - TANGO_HOST=tango_database:10000
      - REDIS_HOST=config_database

  tango_database:
    image: skasip/tango_database:1.0.4
    environment:
      - MYSQL_HOST=tango_mysql:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango_db

  tango_mysql:
    image: skasip/tango_mysql:1.0.3
    environment:
      - MYSQL_ROOT_PASSWORD=sip1
    volumes:
      - tangodb:/var/lib/mysql

  config_database:
    image: redis:4.0.6-alpine
    volumes:
      - config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    ports:
    - 8081:8081

volumes:
  config_database:
  tangodb:
