version: '3.4'

services:

  prometheus:
    image: sip-prometheus
    ports:
      - 9090:9090
    build: prometheus

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  alarm_receiver:
    image: sip-alarm-receiver
    build: alarm_receiver
    ports:
      - 9095:9095
    depends_on:
      - "kafka"

  alert_manager:
    image: sip-alert-manager
    build: alert_manager
    ports:
      - 9093:9093

  demo:
    image: demo-app
    build: demo_app
    depends_on:
      - "pushgateway"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

