version: '3.6'

services:

  processing_controller:
    image: skasip/processing_controller:1.1.2
    environment:
    - REDIS_HOST=config_database
    volumes:
    - ./../../sip/execution_control/processing_controller/processing_block_controller:/home/sip/processing_block_controller
    - ./../../sip/execution_control/processing_controller/scheduler:/home/sip/scheduler
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: fluentd
    depends_on:
    - config_database

  processing_block_controller:
    image: skasip/processing_block_controller:1.1.2
    environment:
    - CELERY_BROKER=redis://processing_block_controller_broker/0
    - CELERY_BACKEND=redis://processing_block_controller_backend/0
    - REDIS_HOST=config_database
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./../../sip/execution_control/processing_controller/processing_block_controller:/home/sip/processing_block_controller
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: fluentd
    depends_on:
    - config_database
    - processing_block_controller_broker
    - processing_block_controller_backend

  processing_block_controller_broker:
    image: redis:4.0.6-alpine
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: fluentd
    volumes:
    - sip_pbc_broker:/data/db

  processing_block_controller_backend:
    image: redis:4.0.6-alpine
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: fluentd
    volumes:
    - sip_pbc_backend:/data/db

  tango_subarray:
    image: skasip/tango_subarray:1.1.2
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ./../../sip/tango_control/tango_subarray/app:/home/sip/app
    logging:
      driver: fluentd
    depends_on:
    - config_database
    - tango_database

  tango_processing_block:
    image: skasip/tango_processing_block:1.1.2
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ./../../sip/tango_control/tango_processing_block/app:/home/sip/app
    logging:
      driver: fluentd
    depends_on:
    - config_database
    - tango_database

  master_controller:
    image: skasip/master_controller:1.1.2
    command: ["-v"]
    environment:
    - REDIS_HOST=config_database
    - REDIS_PORT=6379
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ./../../sip/execution_control/master_controller/app:/home/sip/app
    logging:
      driver: fluentd
    depends_on:
    - config_database

  flask_master:
    image: skasip/flask_master:1.1.2
    ports:
      - 5000:5000
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ./../../sip/tango_control/flask_master/app:/home/sip/app
    logging:
      driver: fluentd
    depends_on:
    - config_database

  tango_master:
    image: skasip/tango_master:1.1.2
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ./../../sip/tango_control/tango_master/app:/home/sip/app
    logging:
      driver: fluentd
    depends_on:
    - config_database
    - tango_database

  tango_database:
    image: skasip/tango_database:1.0.4
    ports:
    - 10000:10000
    environment:
    - MYSQL_HOST=tango_mysql:3306
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - MYSQL_DATABASE=tango_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
    depends_on:
    - tango_mysql

  tango_mysql:
    image: skasip/tango_mysql:1.0.3
    environment:
    - MYSQL_ROOT_PASSWORD=sip1
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - sip_tango_mysql:/var/lib/mysql:consistent

  config_database:
    image: redis:4.0.6-alpine
    deploy:
      mode: replicated
      replicas: 1
    ports:
    - 6379:6379
    volumes:
    - sip_config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander
    ports:
    - 8081:8081
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
    - config_database

  fluentd:
    image: fluent/fluentd:v1.3
    ports:
      - 24224:24224
    environment:
    - FLUENTD_CONF=sip.conf
    deploy:
      replicas: 1
    configs:
    - source: fluentd
      target: "/fluentd/etc/sip.conf"
      mode: 0644

volumes:
  sip_config_database:
  sip_pbc_broker:
  sip_pbc_backend:
  sip_tango_mysql:

configs:
  fluentd:
    file: ./../../sip/platform/fluentd/sip.conf
