version: '3.3'

services:

  config_database:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: config_database
        target: /data/db

  config_database1:
    image: redis:4.0.6-alpine
    ports:
      - 6377:6377
    volumes:
      - type: volume
        source: config_database1
        target: /data/db

  config_database2:
    image: redis:4.0.6-alpine
    ports:
      - 6376:6376
    volumes:
      - type: volume
        source: config_database2
        target: /data/db

