version: '3.6'

services:

    scheduler:
        image: skasip/dask_scheduler_base

        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M

        networks:
            hostnet: {}

    worker:
        image: skasip/dask_workflow_test_02

        command: ["sh", "-c", "dask-worker --nprocs 1 --nthreads 2 --memory-limit 2GB $${DASK_SCHEDULER_HOST}:$${DASK_SCHEDULER_PORT}"]
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        networks:
            hostnet: {}

networks:
    hostnet:
        external: true
        name: host
