#!/bin/sh
# start containers for the master interface service (Rest Variant)

mcpath=../../master_controller_service
mipath=.
dbpath=../../configuration_db/redis


# Build and run docker images
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build && \
            (cd ${dbpath}/config_db/utils; python3 set_initial_data.py)
