version: '3.6'

services:

    workflow:
        image: skasip/dask_workflow_test_02
        entrypoint: python3
        command: -m workflow
        # If running using host networking the scheduler hostname / IP
        # cannot use overlay service discovery
        environment:
            - DASK_SCHEDULER_HOST=localhost
            - DASK_SCHEDULER_PORT=8786
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
            restart_policy:
                condition: none
        networks:
            - hostnet


networks:
    hostnet:
        external: true
        name: host
