version: '3.6'

services:

    scheduler:
        image: skasip/dask_scheduler_base
        ports:
            - 8787
            - 8786
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        # healthcheck based curl of boken interface
        networks:
            - workflow_02

    worker:
        image: skasip/dask_workflow_test_02
        entrypoint: dask-worker
        command: --nprocs 1 --nthreads 2 --memory-limit 2GB scheduler:8786
        depends_on:
            - scheduler
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
        networks:
            - workflow_02

networks:
    workflow_02:
        external: true