version: '3.6'

services:

  tango_subarray:
    image: skasip/tango_subarray:1.1.2
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ../../../sip/tango_control/tango_subarray/app:/home/sip/app
    depends_on:
    - config_database
    - tango_database

  master_controller:
    image: skasip/master_controller:1.1.2
    command: ["-v"]
    environment:
    - REDIS_HOST=config_database
    - REDIS_PORT=6379
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ../../../sip/execution_control/master_controller/app:/home/sip/app
    depends_on:
    - config_database

  tango_master:
    image: skasip/tango_master:1.1.2
    environment:
    - TANGO_HOST=tango_database:10000
    - REDIS_HOST=config_database
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ../../../sip/tango_control/tango_master/app:/home/sip/app
    depends_on:
    - config_database
    - tango_database

  tango_database:
    image: skasip/tango_database:1.0.4
    ports:
    - 10000:10000
    environment:
    - MYSQL_HOST=tango_mysql:3306
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - MYSQL_DATABASE=tango_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
    depends_on:
    - tango_mysql

  tango_mysql:
    image: skasip/tango_mysql:1.0.3
    environment:
    - MYSQL_ROOT_PASSWORD=sip1
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - tangodb:/var/lib/mysql:consistent

  config_database:
    image: redis:4.0.6-alpine
    deploy:
      mode: replicated
      replicas: 1
    ports:
    - 6379:6379
    volumes:
    - config_database:/data/db

  redis-commander-db0:
    image: rediscommander/redis-commander
    ports:
    - 8081:8081
    environment:
    - REDIS_HOSTS=config_db:config_database:6379:0
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
    - config_database

volumes:
  config_database:
  tangodb:
