version: '3.6'

services:

  recv:
    image: skasip/ingest_visibilities
    volumes:
      - type: bind
        source: /etc
        target: /app/output
    deploy:
        mode: replicated
        replicas:
        placement:
          constraints: [node.labels.recv == true]
    networks:
      - hostnet

networks:
      hostnet:
        external: true
        name: host
