#!/bin/bash
# Command line utility to access the flask interface root for SDP State.
# Uses curl and jq.

: ${DOCKER_HOST:=localhost}
url2=${DOCKER_HOST%:*}:5000/
URL=http://${url2#*//}
unset url2

curl -s "$URL" | jq .


