version: '3.4'

services:

  master:
    image: skasip/master_interface_service
    environment:
      REDIS_HOST: "master_db"
    ports:
      - 5000
    build: .

  master_db:
    image: redis:4.0.6-alpine
    volumes:
      - master_db:/data/db

  services_watchdog:
    image: skasip/master_controller_service
    environment:
      REDIS_HOST: "master_db"
    build: ../../master_controller_service

volumes:
  master_db:
