#!/bin/sh
# start containers for the master interface service (Rest Variant)

mcpath=../../master_controller_service
mipath=.
dbpath=../../configuration_db/redis


# Build and run docker images
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build && \
            (mytmpdir=$(mktemp -d --tmpdir venv.XXXXXXXXXX )
            python3 -m venv $mytmpdir && \
            $mytmpdir/bin/pip install skasip-config-db && \
            $mytmpdir/bin/skasip_config_db_init && \
            rm -rf $mytmpdir)
