---
# file: ska.sip/tasks/main.yml

# http://docs.ansible.com/ansible/docker_image_module.html
#- name: Build SIP docker image (This takes quite a long time...)
#  become: yes
#  shell: chdir={{ ansible_user_dir }}/integration-prototype.git docker build . -t sip

# Install requests
# - name: Install requests
#   become: yes
#   shell: pip install requests

# Install docker-py
# - name: Install docker-py
#   become: yes
#  shell: pip install docker-py

# Pulling latest image from Docker Hub
- name: Download SIP docker image
  become: yes
  shell: docker pull njthykkathu/vis_test:latest

# Increase rmem_max
- name: Increasing rmem_max
  become: yes
  shell: sysctl net.core.rmem_max=33554432

# Increase rmem_default
- name: Increasing the rmem_default
  become: yes
  shell: sysctl net.core.rmem_default=8388608

# Increase wmem_max
- name: Increasing wmem_max
  become: yes
  shell: sysctl net.core.wmem_max=524288

# Assign label to the swarm nodes
- name: Asign labels to swarm nodes | if any
  become: yes
  command: docker node update --label-add {{ item }}=true {{ ansible_nodename }}
  changed_when: False
  with_items:
    - "{{ swarm_labels  | default([]) }}"
  delegate_to: "{{ groups['swarm_leader'][0] }}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels
  
