FROM ubuntu:18.04
LABEL maintainer="Vlad Stolyarov"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install dask distributed

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install ARL requirements
COPY pipelines/requirements.arl.min.txt ./requirements.txt
RUN pip3 install -r requirements.txt
