FROM ubuntu:18.04
LABEL maintainer="Vlad Stolyarov"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install -U pip && \
    pip install dask distributed

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /pipelines

# Install ARL requirements
COPY pipelines/requirements.arl.min.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy pipeline scripts
COPY pipelines/*.py ./
