FROM ubuntu
MAINTAINER Vlad Stolyarov
USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update
RUN apt-get -y install docker
RUN apt-get -y install python3 python3-pip python3-tk
RUN apt-get -y install libboost-program-options-dev
RUN apt-get -y install python3-numpy-dev
RUN apt-get -y install git
RUN apt-get -y install nano
RUN apt-get -y install graphviz
RUN apt-get -y install libpng-dev
RUN apt-get -y install sed
RUN apt-get -y install wget
RUN pip3 install pip --upgrade
RUN pip3 install dask distributed --upgrade
RUN pip3 install bokeh
RUN adduser --disabled-password -gecos 'unprivileged user' sdp

WORKDIR /home/sdp
RUN mkdir -p /home/sdp/algorithm-reference-library/data_models
RUN mkdir -p /home/sdp/algorithm-reference-library/data
RUN mkdir -p /home/sdp/algorithm-reference-library/libs
RUN mkdir -p /home/sdp/algorithm-reference-library/processing_components
RUN mkdir -p /home/sdp/algorithm-reference-library/test_results
COPY algorithm-reference-library/requirements.txt  algorithm-reference-library/requirements.txt

WORKDIR /home/sdp/algorithm-reference-library
RUN pip3 install -r requirements.txt

WORKDIR /usr/lib/python3.6
RUN ln -s /home/sdp/algorithm-reference-library/data_models
RUN ln -s /home/sdp/algorithm-reference-library/data
RUN ln -s /home/sdp/algorithm-reference-library/libs
RUN ln -s /home/sdp/algorithm-reference-library/processing_components
RUN ln -s /home/sdp/algorithm-reference-library/test_results

WORKDIR /home/sdp
# Copy the pipelines
#COPY pipelines/ pipelines/
RUN mkdir -p pipelines

RUN jupyter notebook --generate-config
RUN sed -i -e 's/#c.NotebookApp.ip = \x27localhost\x27/c.NotebookApp.ip = \x27*\x27/' /root/.jupyter/jupyter_notebook_config.py
RUN sed -i -e 's/#c.NotebookApp.allow_root = False/c.NotebookApp.allow_root = True/' /root/.jupyter/jupyter_notebook_config.py
RUN sed -i -e 's/#c.NotebookApp.password = \x27\x27/c.NotebookApp.password = \x27sha1:d347247f2e85:67b7832acf5f0e9294abd34f878ba7d32860d1f3\x27/' /root/.jupyter/jupyter_notebook_config.py
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV ARL_DASK_SCHEDULER=172.18.0.3:8786
ENTRYPOINT ["/home/sdp/pipelines/ical-pipeline.py"]
#ENTRYPOINT ["/bin/bash"]

