FROM ubuntu:18.04
LABEL maintainer="Vlad Stolyarov"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install dask distributed

RUN pip3 install bokeh

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT ["dask-scheduler"]
