version: '3.3'

services:

  redis_configuration_database:
    image: njthykkathu/init_db
    environment:
      REDIS_HOST: "redis://config_database"
      REDIS_DB_ID: 0
    ports:
      - 5000
    build: .

  config_database:
    image:  redis:4.0.6-alpine
    volumes:
      - config_database:/data/db

volumes:
  config_database:
